trigger:
  - main
stages:
    - stage: BuildStage
      jobs:
        - job: BuildJob
          pool:
               vmImage: 'ubuntu-latest'
          steps:
             - task: Npm@1
               inputs:
                 command: 'install'
             - task: CmdLine@2
               inputs:
                 script: |
                   pwd
                   ls -al
             - task: Npm@1
               inputs:
                  command: 'custom'
                  customCommand: 'run build'
             - task: CmdLine@2
               inputs:
                 script: |
                   pwd
                   ls -al